
function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("handler#title", "load")
end

function on_message(self, message_id, message,sender)
	if(message_id == hash("showdialogue"))then
		msg.post("handler#title", "unload")
		msg.post("handler#dialogue", "load")
	elseif(message_id == hash("showtitle"))then
		msg.post("handler#dialogue", "unload")
		msg.post("handler#title", "load")
	elseif message_id == hash("proxy_loaded")then
		msg.post(sender, "enable")
	end
end	
